# Generated by Django 5.2.8 on 2025-11-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
